{{- if .Values.snapshot.enabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.snapshot.snapshotController.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.snapshot.snapshotController.name}}
    {{- include "azurefile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.snapshot.snapshotController.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.snapshot.snapshotController.name}}
      {{- include "azurefile.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.snapshot.snapshotController.name}}
        {{- include "azurefile.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.snapshotController }}
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
{{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.controller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.snapshot.snapshotController.name}}
{{- if eq .Values.snapshot.apiVersion "beta" }}
  {{- if hasPrefix "/" .Values.snapshot.image.csiSnapshotController.repository }}
          image: "{{ .Values.image.baseRepo }}{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.tag }}"
  {{- else }}
          image: "{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.tag }}"
  {{- end }}
{{- else }}
  {{- if hasPrefix "/" .Values.snapshot.image.csiSnapshotController.repository }}
          image: "{{ .Values.image.baseRepo }}{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.gaTag }}"
  {{- else }}
          image: "{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.gaTag }}"
  {{- end }}
{{- end }}
          args:
            - "--v=2"
            - "--leader-election=true"
          resources: {{- toYaml .Values.snapshot.snapshotController.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.snapshot.image.csiSnapshotController.pullPolicy }}
{{- end -}}
