---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
  labels:
    {{- include "azurefile.labels" . | nindent 4 }}
  annotations:
    csiDriver: "{{ .Values.image.azurefile.tag }}"
{{- if eq .Values.snapshot.apiVersion "beta" }}
    snapshot: "{{ .Values.snapshot.image.csiSnapshotter.tag }}"
{{- else }}
    snapshot: "{{ .Values.snapshot.image.csiSnapshotter.gaTag }}"
{{- end }}
spec:
  attachRequired: {{ .Values.controller.attachRequired }}
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
