version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
  open-pull-requests-limit: 1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
  open-pull-requests-limit: 1
- package-ecosystem: "docker"
  directory: "/pkg/azurefileplugin/"
  schedule:
    interval: "daily"
    time: "01:00"
    timezone: "Asia/Shanghai"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
    - "kind/cleanup"

- package-ecosystem: pip
  directory: /hack
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /pkg/azurefileplugin
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /vendor/github.com/pelletier/go-toml
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /vendor/golang.org/x/net/http2
  schedule:
    interval: daily
