---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  mountOptions:
    - nconnect=4
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical share in the cluster
    # the # character is reserved for internal use
    volumeHandle: account-name_file-share-name
    volumeAttributes:
      resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
      shareName: EXISTING_FILE_SHARE_NAME  # only file share name, don't use full path
      protocol: nfs
