---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-premiumv2
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: PremiumV2_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
