---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-azurefile-node
  namespace: kube-system
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-azurefile-node
  template:
    metadata:
      labels:
        app: csi-azurefile-node
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: Default
      serviceAccountName: csi-azurefile-node-sa
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - operator: "Exists"
      initContainers:
        - name: install-azurefile-proxy
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.34.1
          imagePullPolicy: IfNotPresent
          command:
            - "/azurefile-proxy/init.sh"
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          env:
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
            - name: AZNFS_NONINTERACTIVE_INSTALL
              value: "1"
            - name: INSTALL_AZUREFILE_PROXY
              value: "true"
            - name: INSTALL_AZNFS_MOUNT
              value: "true"
            - name: ENABLE_MI_AUTH
              value: "true"
          volumeMounts:
            - name: host-usr
              mountPath: /host/usr
            - name: host-etc
              mountPath: /host/etc
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/livenessprobe:v2.17.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29613
            - --v=2
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/csi-node-driver-registrar:v2.15.0
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/file.csi.azure.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: azurefile
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.34.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--enable-azurefile-proxy=true"
            - "--azurefile-proxy-endpoint=$(AZUREFILE_PROXY_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--metrics-address=0.0.0.0:29615"
            - "--enable-kata-cc-mount=true"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29613
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: AZURE_CREDENTIAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: azure-cred-file
                  key: path
                  optional: true
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: AZUREFILE_PROXY_ENDPOINT
              value: unix:///csi/azurefile-proxy.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /etc/kubernetes/
              name: azure-cred
            - mountPath: /dev
              name: device-dir
            - mountPath: /run/kata-containers/shared/direct-volumes
              name: kata-direct-volumes
            - name: azfilesauth
              mountPath: /etc/azfilesauth
            - name: log-dir
              mountPath: /var/log/
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: azfilesrefresh
          image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.34.1
          imagePullPolicy: IfNotPresent
          command:
            - "azfilesrefresh"
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - name: azfilesauth
              mountPath: /etc/azfilesauth
            - name: log-dir
              mountPath: /var/log/
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: host-usr
          hostPath:
            path: /usr
        - name: host-etc
          hostPath:
            path: /etc
        - name: azfilesauth
          hostPath:
            path: /etc/azfilesauth
            type: DirectoryOrCreate
        - hostPath:
            path: /var/lib/kubelet/plugins/file.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /etc/kubernetes/
            type: DirectoryOrCreate
          name: azure-cred
        - hostPath:
            path: /dev
            type: Directory
          name: device-dir
        - name: kata-direct-volumes
          hostPath:
            path: /run/kata-containers/shared/direct-volumes/
            type: DirectoryOrCreate
        - hostPath:
            path: /var/log/
            type: DirectoryOrCreate
          name: log-dir
---
