---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: file.csi.azure.com
  annotations:
    csiDriver: v1.30.0
    snapshot: v6.2.2
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  fsGroupPolicy: ReadWriteOnceWithFSType
