name: MacOS Build & Unit Test
on:
    pull_request: {}
    push: {}
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Set up Go 1.x
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build Test
        run: |
          make azurefile-darwin
      - name: Run unit tests on MacOS
        run: go test -v -race ./pkg/...
