name: MacOS Build & Unit Test
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ^1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build Test
        run: |
          make azurefile-darwin
      - name: Run unit tests on MacOS
        run: go test -v -race ./pkg/... -timeout=30m
