name: ShellCheck
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
      env:
         SHELLCHECK_OPTS: -e SC2034
      with:
        severity: warning
        check_together: 'yes'
        disable_matcher: false
        ignore_paths: vendor release-tools hack
        format: gcc
