name: Windows Build & Unit Test

on:
    pull_request: {}
    push: {}

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.16.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Set up Go 1.x
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ^1.16
        id: go
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Build
        run: |
          go build -a -o _output/azurefileplugin.exe ./pkg/azurefileplugin    
      - name: Run Windows Unit Tests
        run: |
          # start the CSI Proxy before running tests on windows
          Start-Job -Name CSIProxy -ScriptBlock {
            Invoke-WebRequest https://acs-mirror.azureedge.net/csi-proxy/v1.1.1./binaries/csi-proxy-v1.1.1.tar.gz -OutFile csi-proxy.tar.gz;
            tar -xvf csi-proxy.tar.gz
            .\bin\csi-proxy.exe --kubelet-path $pwd --v=5
          };

          Start-Sleep -Seconds 30;

          Write-Output "getting named pipes"
          [System.IO.Directory]::GetFiles("\\.\\pipe\\")

          go test -v -race ./pkg/...
