{{- if .Values.snapshot.enabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.snapshot.snapshotController.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.snapshot.snapshotController.name}}
    {{- include "azurefile.labels" . | nindent 4 }}
{{- with .Values.snapshot.snapshotController.labels }}
{{ . | toYaml | indent 4 }}
{{- end }}
{{- with .Values.snapshot.snapshotController.annotations }}
  annotations:
{{ . | toYaml | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.snapshot.snapshotController.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.snapshot.snapshotController.name}}
      {{- include "azurefile.selectorLabels" . | nindent 6 }}
  # the snapshot controller won't be marked as ready if the v1 CRDs are unavailable
  # in #504 the snapshot-controller will exit after around 7.5 seconds if it
  # can't find the v1 CRDs so this value should be greater than that
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: {{ .Values.snapshot.snapshotController.strategyType }}
  template:
    metadata:
      labels:
        app: {{ .Values.snapshot.snapshotController.name}}
        {{- include "azurefile.labels" . | nindent 8 }}
{{- with .Values.snapshot.snapshotController.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.snapshot.snapshotController.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.snapshotController }}
      nodeSelector:
        kubernetes.io/os: linux
    # runOnControlPlane=true or runOnMaster=true only takes effect if affinity is not set
    {{- if contains (tpl "{{ .Values.controller.affinity }}" .) "nodeSelectorTerms" }}
      {{- with .Values.controller.affinity }}
      affinity:
      {{ toYaml . | indent 8 }}
      {{- end }}
    {{- else if or .Values.controller.runOnControlPlane .Values.controller.runOnMaster}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                {{- if .Values.controller.runOnControlPlane}}
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
                {{- end}}
                {{- if .Values.controller.runOnMaster}}
                - key: node-role.kubernetes.io/master
                  operator: Exists
                {{- end}}
    {{- end }}
      priorityClassName: system-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
{{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.snapshot.snapshotController.name}}
{{- if hasPrefix "/" .Values.snapshot.image.csiSnapshotController.repository }}
          image: "{{ .Values.image.baseRepo }}{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.tag }}"
{{- else }}
          image: "{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.tag }}"
{{- end }}
          args:
            - "--v=2"
            - "--leader-election=true"
            - "--leader-election-namespace={{ .Release.Namespace }}"
          resources: {{- toYaml .Values.snapshot.snapshotController.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.snapshot.image.csiSnapshotController.pullPolicy }}
          securityContext:
            capabilities:
              drop:
              - ALL
{{- end -}}
